services:
    build-rms:
        build:
            context: .
            dockerfile: Dockerfile
        image: maythetnaingbo/rms-docker-img:v7
        container_name: rms-docker-container
        ports:
            - "8000:5050"
