name: Automatic Testing for Food Blog Web App

on:
    push:
        branches:
            - main # Trigger on push to the main branch
    pull_request: # Trigger on pull request to the main branch
        branches:
            - main

jobs:
    test:
        runs-on: windows-latest # Use a Windows runner

        steps:
            # Step 1: Checkout code from the repository
            - name: Checkout code from GitHub Repo
              uses: actions/checkout@v3

            # Step 2: Setup Node.js environment
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            # Step 3: Remove the existing node_modules folder (if necessary)
            - name: Remove existing node_modules folder
              run: if exist node_modules (rmdir /S /Q node_modules)

            # Step 4: Install dependencies from package.json
            - name: Install dependencies
              run: npm install

            # Step 5: Run backend tests
            - name: Run backend tests
              run: npm run backend-test

            # Step 6: Run frontend tests
            - name: Run frontend tests
              run: npm run frontend-test

            # Step 7: Generate coverage report
            - name: Generate coverage report
              run: npm run coverage-report
