name: Automatic Testing for Food Blog Web App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

    
      - name: Run Frontend Tests
        run: npm run frontend-test

      - name: Generate Coverage Report
        run: npm run coverage-report
