name: Automatic Testing for Food Blog Web App

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Clean Coverage Data
              run: rm -rf coverage/ .nyc_output

            - name: Install Dependencies
              run: npm install

            - name: Pre-Instrument Frontend Files
              run: npm run frontend-instrument

            - name: Run Frontend Tests
              run: npm run frontend-test

            - name: Debug .nyc_output
              run: ls -R .nyc_output

            - name: Generate Coverage Report
              run: npm run coverage-report
