global:
    scrape_interval: 15s # How often to scrape targets by default.
    evaluation_interval: 15s # How often to evaluate rules by default.

scrape_configs:
    - job_name: "nodejs-app" # Descriptive name for the job
      static_configs:
          - targets: ["build-rms:5050"] # Replace with the container name and port of your Node.js app
